
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARGUMENTS BLOCK CLOCKFREQUENCY DELAY DESCRIPTION DUTYCYCLE EXPECTEDRESULT NAME NUMBER PIN REPEAT STRING TIMERDURATION TIMERID TRIGGERblock : BLOCK NAME\n             | BLOCK NAME DESCRIPTION\n             | BLOCK NAME EXPECTEDRESULT\n             | BLOCK NAME DELAY NUMBER\n             | BLOCK NAME REPEAT NUMBER\n             | BLOCK NAME TIMERID NUMBER\n             | BLOCK NAME TIMERDURATION NUMBER\n             | BLOCK NAME PIN NAME\n             | BLOCK NAME TRIGGER NAME\n             | BLOCK NAME CLOCKFREQUENCY NAME\n             | BLOCK NAME DUTYCYCLE NUMBER\n    '
    
_lr_action_items = {'BLOCK':([0,],[2,]),'$end':([1,3,4,5,14,15,16,17,18,19,20,21,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,]),'NAME':([2,10,11,12,],[3,18,19,20,]),'DESCRIPTION':([3,],[4,]),'EXPECTEDRESULT':([3,],[5,]),'DELAY':([3,],[6,]),'REPEAT':([3,],[7,]),'TIMERID':([3,],[8,]),'TIMERDURATION':([3,],[9,]),'PIN':([3,],[10,]),'TRIGGER':([3,],[11,]),'CLOCKFREQUENCY':([3,],[12,]),'DUTYCYCLE':([3,],[13,]),'NUMBER':([6,7,8,9,13,],[14,15,16,17,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'block':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> block","S'",1,None,None,None),
  ('block -> BLOCK NAME','block',2,'p_block','parser.py',66),
  ('block -> BLOCK NAME DESCRIPTION','block',3,'p_block','parser.py',67),
  ('block -> BLOCK NAME EXPECTEDRESULT','block',3,'p_block','parser.py',68),
  ('block -> BLOCK NAME DELAY NUMBER','block',4,'p_block','parser.py',69),
  ('block -> BLOCK NAME REPEAT NUMBER','block',4,'p_block','parser.py',70),
  ('block -> BLOCK NAME TIMERID NUMBER','block',4,'p_block','parser.py',71),
  ('block -> BLOCK NAME TIMERDURATION NUMBER','block',4,'p_block','parser.py',72),
  ('block -> BLOCK NAME PIN NAME','block',4,'p_block','parser.py',73),
  ('block -> BLOCK NAME TRIGGER NAME','block',4,'p_block','parser.py',74),
  ('block -> BLOCK NAME CLOCKFREQUENCY NAME','block',4,'p_block','parser.py',75),
  ('block -> BLOCK NAME DUTYCYCLE NUMBER','block',4,'p_block','parser.py',76),
]
